version: 1
formatters:
  default:
    format: "[%(asctime)s] %(levelname)s in %(module)s.%(funcName)s Line %(lineno)s: %(message)s"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/backend.log
    formatter: default
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
root:
  level: DEBUG
  handlers: [file, console]